### ISSUE TITLE
ThumbAsset vague.

### ISSUE THREAD

**Issue by Xue-Felix** [ihsankottupadam/flutter-gradient-slider#2]
ThumbAsset has been configured, but the effect is very blurry. It seems that the image has been compressed severely?
 
 
<img width="117" alt="image" src="https://github.com/user-attachments/assets/c9ffaf54-f15a-4b2f-85bb-41860f62ca1b" />

**Comment by ihsankottupadam** [comment]
Fixed the blurry ThumbAsset issue in 1.0.3. Thanks for your feedback
